name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Install packages
      run: npm ci
    
    - name: Test code
      run: npm test -- --browsers ChromeHeadless --watch=false
      
    - name: Build project
      run: npm run build -- --prod

    - name: Upload artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: ${{ secrets.ARTIFACT_NAME }}
        path: dist/
        if-no-files-found: error
